CREATE DATABASE IF NOT EXISTS ragdb;
USE ragdb;

CREATE TABLE docs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255),
  content MEDIUMTEXT,
  embedding VECTOR(1536),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE docs ADD FULLTEXT (title, content);
